// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ddnf
NumericVector ddnf(NumericVector x, double df1, double df2, double ncp1, double ncp2);
RcppExport SEXP sadists_ddnf(SEXP xSEXP, SEXP df1SEXP, SEXP df2SEXP, SEXP ncp1SEXP, SEXP ncp2SEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP );
        Rcpp::traits::input_parameter< double >::type df1(df1SEXP );
        Rcpp::traits::input_parameter< double >::type df2(df2SEXP );
        Rcpp::traits::input_parameter< double >::type ncp1(ncp1SEXP );
        Rcpp::traits::input_parameter< double >::type ncp2(ncp2SEXP );
        NumericVector __result = ddnf(x, df1, df2, ncp1, ncp2);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
