# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ddnf <- function(x, df1, df2, ncp1, ncp2) {
    .Call('sadists_ddnf', PACKAGE = 'sadists', x, df1, df2, ncp1, ncp2)
}

